export const CREAR_USUARIO = 'CREAR_USUARIO';
export const CREAR_USUARIO_EXITO = 'CREAR_USUARIO_EXITO';
export const CREAR_USUARIO_ERROR = 'CREAR_USUARIO_ERROR';

export const MOSTRAR_USUARIOS = 'MOSTRAR_USUARIOS';
export const MOSTRAR_USUARIOS_EXITO = 'MOSTRAR_USUARIOS_EXITO';
export const MOSTRAR_USUARIOS_ERROR = 'MOSTRAR_USUARIOS_ERROR';

export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const EDITAR_USUARIOS_EXITO = 'EDITAR_USUARIOS_EXITO';
export const EDITAR_USUARIOS_ERROR = 'EDITAR_USUARIOS_ERROR';

export const OBTENER_USUARIO_BORRAR = 'OBTENER_USUARIO_BORRAR';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const ELIMINAR_USUARIOS_EXITO = 'ELIMINAR_USUARIOS_EXITO';
export const ELIMINAR_USUARIOS_ERROR = 'ELIMINAR_USUARIOS_ERROR';